export const NAMES: Record<string, string> = {
  'sinmos-finished': 'Sistema Integrado de Monitoramento e Segurança Finalizado',
  'sinmos-remastered-next': 'Sistema Integrado de Monitoramento e Segurança para WEB',
  'sinmos-remastered-react-native': 'Sistema Integrado de Monitoramento e Segurança para MOBILE',
  'sinmos-remastered-api': 'RestAPI do Sistema Integrado de Monitoramento e Segurança',
  lucaserm: 'Configuração do Github',
  'pomodoro-react-ts': 'Pomodoro para WEB',
  'hotel-php': 'Sistema de Hotel para WEB',
  'instahub-reactnative': 'Instahub para MOBILE',
  'biblioteca-springboot': 'Sistema de Biblioteca para WEB',
  'todo-app-express': 'Lista de Tarefas',
  'calculadora-js-basica': 'Calculadora JS',
  'landing-page-noframewok': 'Landing Page sem Framework',
  'exemplo-posts-react': 'Posts com React',
  sinmos: 'Protótipo do Sistema Integrado de Monitoramento e Segurança',
  skyblog: 'SkyBlog: ChatGPT Post Generator',
  'my-docs': 'Documentação Pessoal',
  'my-finance': 'Projeto para Organização Pessoal das Finanças',
  'my-docs-comedyhub': 'Documentação Pessoal - ComedyHub',
  'next-tutorial': 'Tutorial para Desenvolvimento em NextJS',
};
